# Generated by Django 5.0.3 on 2024-04-11 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact1", models.CharField(max_length=20)),
                ("contact2", models.CharField(blank=True, max_length=20, null=True)),
                ("address1", models.CharField(max_length=100)),
                ("address2", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
