# Generated by Django 5.0.3 on 2024-04-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="national_id",
            field=models.CharField(blank=True, default=None, max_length=30),
        ),
    ]
