# Generated by Django 5.0.1 on 2024-02-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("breed", models.CharField(max_length=250)),
                ("age", models.IntegerField()),
                ("weight", models.FloatField()),
                ("gender", models.CharField(max_length=10)),
                ("health_info", models.TextField()),
                ("color", models.CharField(max_length=30)),
                ("video", models.CharField(blank=True, default="", max_length=100)),
                ("pictures", models.TextField(blank=True)),
                ("status", models.BooleanField(default=True)),
            ],
        ),
    ]
