# Generated by Django 5.0.3 on 2024-04-28 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0002_animal_user_alter_animal_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animal",
            name="pictures",
        ),
        migrations.AlterField(
            model_name="animal",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="AnimalImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="animal_images")),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="animals.animal",
                    ),
                ),
            ],
        ),
    ]
