# Generated by Django 5.0.3 on 2024-04-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0003_remove_animal_pictures_alter_animal_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="price",
            field=models.FloatField(default=100),
        ),
    ]
